namespace HSEModel
{
    /// <summary>
    /// The risk.
    /// </summary>
    public abstract class Risk
    {
        /// <summary>
        /// Gets or sets a value indicating whether [action closed].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [action closed]; otherwise, <c>false</c>.
        /// </value>
        public bool ActionClosed { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [action taken english].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [action taken english]; otherwise, <c>false</c>.
        /// </value>
        public bool ActionTakenEnglish { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [action taken local].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [action taken local]; otherwise, <c>false</c>.
        /// </value>
        public bool ActionTakenLocal { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="Risk"/> is area.
        /// </summary>
        /// <value>
        ///   <c>true</c> if area; otherwise, <c>false</c>.
        /// </value>
        public bool Area { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [at fault identifier].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [at fault identifier]; otherwise, <c>false</c>.
        /// </value>
        public bool AtFaultId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="Risk"/> is attachments.
        /// </summary>
        /// <value>
        ///   <c>true</c> if attachments; otherwise, <c>false</c>.
        /// </value>
        public bool Attachments { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [business stream].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [business stream]; otherwise, <c>false</c>.
        /// </value>
        public bool BusinessStream { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [business unit].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [business unit]; otherwise, <c>false</c>.
        /// </value>
        public bool BusinessUnit { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [description english].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [description english]; otherwise, <c>false</c>.
        /// </value>
        public bool DescriptionEnglish { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [description local].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [description local]; otherwise, <c>false</c>.
        /// </value>
        public bool DescriptionLocal { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [generated by identifier].
        /// </summary>
        /// <value>
        /// <c>true</c> if [generated by identifier]; otherwise, <c>false</c>.
        /// </value>
        public bool GeneratedById { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [hazard identifier].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [hazard identifier]; otherwise, <c>false</c>.
        /// </value>
        public bool HazardId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [incident type identifier].
        /// </summary>
        /// <value>
        /// <c>true</c> if [incident type identifier]; otherwise, <c>false</c>.
        /// </value>
        public bool IncidentTypeId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [involved person job].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [involved person job]; otherwise, <c>false</c>.
        /// </value>
        public bool InvolvedPersonJob { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [involved person name].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [involved person name]; otherwise, <c>false</c>.
        /// </value>
        public bool InvolvedPersonName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [location description].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [location description]; otherwise, <c>false</c>.
        /// </value>
        public bool LocationDescription { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [location identifier].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [location identifier]; otherwise, <c>false</c>.
        /// </value>
        public bool LocationId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [location type identifier].
        /// </summary>
        /// <value>
        /// <c>true</c> if [location type identifier]; otherwise, <c>false</c>.
        /// </value>
        public bool LocationTypeId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [near miss hazard identifier].
        /// </summary>
        /// <value>
        /// <c>true</c> if [near miss hazard identifier]; otherwise, <c>false</c>.
        /// </value>
        public bool NearMissHazardId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [other hazard].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [other hazard]; otherwise, <c>false</c>.
        /// </value>
        public bool OtherHazard { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [project phase identifier].
        /// </summary>
        /// <value>
        /// <c>true</c> if [project phase identifier]; otherwise, <c>false</c>.
        /// </value>
        public bool ProjectPhaseId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [report date].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [report date]; otherwise, <c>false</c>.
        /// </value>
        public bool ReportDate { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [reported by name].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [reported by name]; otherwise, <c>false</c>.
        /// </value>
        public bool ReportedByName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [risk rating after].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [risk rating after]; otherwise, <c>false</c>.
        /// </value>
        public bool RiskRatingAfter { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [risk rating before].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [risk rating before]; otherwise, <c>false</c>.
        /// </value>
        public bool RiskRatingBefore { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [work related].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [work related]; otherwise, <c>false</c>.
        /// </value>
        public bool WorkRelated { get; set; }
    }
}